### ISSUE TITLE
Script Error : error object is not a string

### ISSUE THREAD

**Issue by Beta-Bella** [Sleepless-Development/sleepless_inventory_addons#10]
Hi dear! 

Ive installed your source today and everything works as expected. There are no underlying breaking issues. 
I just saw, that when we finished a craft ( item a + item b) the result is fine, BUT - we get a serverconsole error - 
And i was wondering if theres a way to fix it ( i know this is just complaining on a highlevel, but i really dont like the errors plopping up hehe) 

We have ox_lib 3.22.1, inventory 2.40.1
ESX Framework, build7969. 

Thank you in advance.
Bella
![Bild_2024-06-13_161132511](https://github.com/Sleepless-Development/sleepless_inventory_addons/assets/128776783/cf2d15a8-7436-45f4-9cf2-fc4de7013662)

**Comment by Demigod916** [comment]
@Beta-Bella hello, can i see your config table for crafting? i cant actually reproduce this error

**Comment by Beta-Bella** [comment]
Sure I will add it in here. Im sorry in advance!  Sent from Mail for Windows From: Austin DunnSent: 13 June 2024 17:36To: Sleepless-Development/sleepless_inventory_addonsCc: Bella; MentionSubject: Re: [Sleepless-Development/sleepless_inventory_addons] Script Error : error object is not a string (Issue ***@***.*** hello, can i see your config table for crafting? i cant actually reproduce this error—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were mentioned.Message ID: ***@***.***>

**Comment by Beta-Bella** [comment]
Sure i will add it here : 

    ['plastic_bottle waterbucket_full'] = {
        duration = 2000,
        client = {
            before = function(recipeData)
            end,
            after = function(recipeData)
            end,
        },
        server = {
            before = function(recipeData)
            end,
            after = function(recipeData)
            end,
        },
        costs = {
            ['plastic_bottle'] = { need = 5, remove = true },
            ['waterbucket_full'] = { need = 1, remove = true },
        },
        result = {
            { name = 'water', amount = 5 },
            { name = 'bucket', amount = 1 }
        },
    },

This is one of the recipies, as told - we get the stuff thats supposed to come out it just throws that error.

**Comment by Demigod916** [comment]
this should be fixed in the latest commuit. im going to do some work on backItems too before i make a release.

**Comment by Beta-Bella** [comment]
Thank you so much! <3
