### ISSUE TITLE
Backitems stuck when I login into my server

### ISSUE THREAD

**Issue by mpcmarques** [Sleepless-Development/sleepless_inventory_addons#8]
With the new update, whenever I spawn into my city with items on the back, they dont disappear even when I drop or equip them.

If I pick an item it works fine, but if I login (spawn) with the item in the inventory it gets stuck in my back.

**Comment by Demigod916** [comment]
@mpcmarques what framework?

**Comment by mpcmarques** [comment]
> @mpcmarques what framework?

QBCore. Also with items carry when bucket is changed the prop disappears

**Comment by Demigod916** [comment]
@riNdes sorry, i dont know how i missed this. this should be fixable for sure
